Checking carthage version exists

diff --git a/script/common/carthage b/script/common/carthage
--- a/script/common/carthage
+++ b/script/common/carthage
@@ -1,13 +1,26 @@
 force_install_carthage ()
 {
   echo ""
-  echo " → Installing carthage '$REQUIRED_CARTHAGE_VERSION'"
+  echo " → Checking carthage version '$REQUIRED_CARTHAGE_VERSION'"
   echo ""
-  curl -s -L -O https://github.com/Carthage/Carthage/releases/download/$REQUIRED_CARTHAGE_VERSION/Carthage.pkg > /dev/null
-  sudo installer -pkg Carthage.pkg -target / > /dev/null
-  rm Carthage.pkg
-  echo "    ✔ carthage '$REQUIRED_CARTHAGE_VERSION' successfully installed"
-  echo ""
+  curl -s --head https://github.com/Carthage/Carthage/releases/download/$REQUIRED_CARTHAGE_VERSION/Carthage.pkg | head -n 1 | grep "HTTP/1.[01] [23].." > /dev/null
+  # on success (page exists), $? will be 0;
+  # on failure (page does not exist or is unreachable), $? will be 1
+  if [ "$?" -eq 0 ]
+  then
+    echo ""
+    echo " → Installing carthage '$REQUIRED_CARTHAGE_VERSION'"
+    echo ""
+    curl -s -L -O https://github.com/Carthage/Carthage/releases/download/$REQUIRED_CARTHAGE_VERSION/Carthage.pkg > /dev/null
+    sudo installer -pkg Carthage.pkg -target / > /dev/null
+    rm Carthage.pkg
+    echo "    ✔ carthage '$REQUIRED_CARTHAGE_VERSION' successfully installed"
+    echo ""
+  else
+    printf "\033[1;31mError: carthage version '$REQUIRED_CARTHAGE_VERSION' does not exist."
+    printf "\033[0m"
+    echo ""
+  fi
 }
 
 uninstall_carthage ()
@@ -65,6 +78,7 @@ check_carthage_version ()
           exit 1
         fi
       fi
+    fi
   else
     if [ "$carthage_installed_version" != "$COMPARE_CARTHAGE_VERSION" ]
     then
