Avoid uninstalling when there is no carthage installed

diff --git a/script/common/carthage b/script/common/carthage
--- a/script/common/carthage
+++ b/script/common/carthage
@@ -44,17 +44,14 @@ check_carthage_version ()
     carthage_installed_version="$carthage_installed_version.0"
   fi
 
-  if [ "$carthage_installed_version" != "$COMPARE_CARTHAGE_VERSION" ]
+  if [ "$carthage_installed_version" == ".0" ]
   then
-    printf "\033[1;31mError: carthage version '$carthage_installed_version' is not equal to '$COMPARE_CARTHAGE_VERSION'"
-    printf "\033[0m"
     if [ ! -z "$NO_CARTHAGE_UPDATE" ]
     then
       exit 1
     else
       if [ ! -z "$FORCE_CARTHAGE_VERSION" ]
       then
-        uninstall_carthage
         force_install_carthage
       else
         echo ""
@@ -63,10 +60,36 @@ check_carthage_version ()
         read update_carthage
         if [ "$update_carthage" == "y" ]
         then
-          uninstall_carthage
           force_install_carthage
         else
           exit 1
+        fi
+      fi
+  else
+    if [ "$carthage_installed_version" != "$COMPARE_CARTHAGE_VERSION" ]
+    then
+      printf "\033[1;31mError: carthage version '$carthage_installed_version' is not equal to '$COMPARE_CARTHAGE_VERSION'"
+      printf "\033[0m"
+      if [ ! -z "$NO_CARTHAGE_UPDATE" ]
+      then
+        exit 1
+      else
+        if [ ! -z "$FORCE_CARTHAGE_VERSION" ]
+        then
+          uninstall_carthage
+          force_install_carthage
+        else
+          echo ""
+          echo ""
+          echo "Would you like to update carthage to version '$REQUIRED_CARTHAGE_VERSION'? [N/y]"
+          read update_carthage
+          if [ "$update_carthage" == "y" ]
+          then
+            uninstall_carthage
+            force_install_carthage
+          else
+            exit 1
+          fi
         fi
       fi
     fi
